# This docker-compose file is for building and running the 
# production-ready image locally for testing purposes.
# Platforms like Liara will only use the root Dockerfile, not this file.

version: '3.8'

services:
  # We only have one service now, which we can call 'app'.
  app:
    # The build context is the current directory ('.') where the root Dockerfile is located.
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futoshiki-app
    restart: unless-stopped
    init: true
    ports:
      # We only need to expose port 8000, as it serves both the API and the frontend.
      - "8000:8000"  
    networks:
      - futoshiki-net

networks:
  futoshiki-net:
    driver: bridge